### ISSUE TITLE
Deserialization method json not working

### ISSUE THREAD

**Issue by martinbeentjes** [StackStorm-Exchange/stackstorm-rabbitmq#2]
Hi,

In my current setup I have one rule.  This rule is using the RabbitMQ sensor. It works when I do not configure a deserialization method. 

```
---
sensor_config:
  host: "10.0.2.2"
  username: "guest"
  password: "guest"
  rabbitmq_queue_sensor:
    queues: "hello"
    deserialization_method: "json"
```

I stored the configuration file in `/opt/stackstorn/configs/rabbitmq.yaml`. When I remove the `"json"`, it works perfectly as I see when `tail -f /var/log/st2/st2rulesengine.log`. Also after adding `"pickle"`, it keeps working.

In the log, I see the trigger. The RabbitMQ message is a String of JSON data:

`'payload': {'queue': 'hello', 'body': '{"sensorowner": "....UUID...", "sensor": {"value": 26.0483}}'}`

I want to have the `body` of the payload to be a JSON object, instead of a String. I need to work with the `value`, which determines to which Slack channel I have to send a message.

Is this something I can achieve using the deserialization method?
